[package]
name = "miden-bridge"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[lib]

[features]
default = []
std = ["miden-assembly/std", "miden-objects/std", "miden-stdlib/std"]
async = ["miden-tx/async"]
# the testing feature is required to enable the account creation pow patch
testing = ["miden-objects/testing", "miden-tx/testing", "miden-lib/testing"]
with-debug-info = ["miden-stdlib/with-debug-info"]

[dependencies]
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["std"] }
miden-objects = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["std"]}
regex = { version = "1.10" }
walkdir = { version = "2.5" }
miden-assembly = "0.13.0"
miden-stdlib = "0.13.1"
miden-tx = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["std"]}

[dev-dependencies]
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["std"] }
miden-objects = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["testing"] }
miden-tx = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1", features = ["std", "testing"]}
miden-prover = { version = "0.11", default-features = false }
vm-processor = { package = "miden-processor", version = "0.11", default-features = false }
winter-maybe-async = { version = "0.10" }


[build-dependencies]
regex = { version = "1.10" }
walkdir = { version = "2.5" }
miden-assembly = "0.13.0"
miden-stdlib = "0.13.1"
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1" }
miden-objects = { git = "https://github.com/0xPolygonMiden/miden-base", tag = "v0.8.1" }

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true



