[package]
name = "miden-tx-sender"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
miden-client = {version = "0.8.1", features = ["concurrent", "sqlite", "tonic"]}
miden-crypto = "0.14"
miden-objects = "0.8.1"
rocket = { version = "0.5.1", features = ["json"] }
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.8.5"
dotenv = "0.15.0"
tokio = "1.44.1"
